name: Build Docker Image for my Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Add this step to debug the generated tag
    - name: Debug image tag
      run: echo "Attempting to use tag: ghcr.io/${{ toLowerCase(github.repository) }}:latest"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Correctly convert the entire repository path (owner/repo_name) to lowercase
        tags: ghcr.io/${{ toLowerCase(github.repository) }}:latest