name: Build Docker Image for my Portfolio

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry or (gHCR))  
      uses: docker/login-action@v3
      with:
        registry: ghcr.io           #  Normally it should be docker.io but i want to use GitHub Container Registry so i changed it to ghcr.io and for the secrets, same account works for github and ghcr, so they'll kind of sync
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true  #  Cross checked and now i gave it permission to push the image to the registry
        tags: ghcr.io/${{ github.repository }}:latest
