name: Build Docker Image for my Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate lowercased image repository path
      id: image_vars # Give an ID to this step to reference its outputs
      run: |
        # Converts "OWNER/REPO_NAME" to "owner/repo_name"
        # The result is set as an output variable 'image_path' for this step
        echo "image_path=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug image tag construction
      # This step will print the exact tag being used, allowing you to verify it's lowercase
      run: echo "Full image tag will be: ghcr.io/${{ steps.image_vars.outputs.image_path }}:latest"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Use the output from the 'image_vars' step
        tags: ghcr.io/${{ steps.image_vars.outputs.image_path }}:latest