name: Test Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # stable and official version

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3  # latest stable

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # v4 is stable and less problematic than v5
        with:
          context: .
          push: TRUE       # boolean, no quotes, lowercase
          tags: ghcr.io/${{ github.repository }}:latest
